<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1665028928513' stop='1665028938435'>
    <name>Android settings test</name>
    <title>Android settings test</title>
    <test-cases>
        <test-case start='1665028928513' status='broken' stop='1665028938434'>
            <name>go to settings app</name>
            <title>go to settings app</title>
            <labels>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-0'/>
            </labels>
            <parameters>
                <parameter kind='argument' name='device' value='MiA2 10.0-10'/>
            </parameters>
            <steps>
                <step start='1665028933515' status='broken' stop='1665028938434'>
                    <name>POST /session/:sessionId/appium/device/start_activity</name>
                    <title>POST /session/:sessionId/appium/device/start_activity</title>
                    <attachments>
                        <attachment title='Request' source='0a1ac4cb-a73d-4c88-ab4a-32b2142382fa-attachment.json' type='application/json' size='102'/>
                    </attachments>
                    <steps>
                        <step start='1665028936875' status='passed' stop='1665028938432'>
                            <name>GET /session/:sessionId/screenshot</name>
                            <title>GET /session/:sessionId/screenshot</title>
                            <attachments>
                                <attachment title='Screenshot' source='0d0c189c-619d-4906-a4bc-1d907ac82870-attachment.png' type='image/png' size='390737'/>
                            </attachments>
                            <steps/>
                        </step>
                    </steps>
                </step>
            </steps>
            <attachments/>
            <failure>
                <message>An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.android.settings/.Settings' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Cannot start the 'com.android.settings/.Settings' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Activity name '.com.android.settings.Settings' used to start the app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity</message>
                <stack-trace>unknown error: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.android.settings/.Settings' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Cannot start the 'com.android.settings/.Settings' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Activity name '.com.android.settings.Settings' used to start the app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity
                    at getErrorFromResponseBody (E:\MyWorkSpace\wdo-samples\wdio-jsappium\node_modules\webdriver\build\utils.js:198:12)
                    at NodeJSRequest._request (E:\MyWorkSpace\wdo-samples\wdio-jsappium\node_modules\webdriver\build\request\index.js:166:60)
                    at processTicksAndRejections (node:internal/process/task_queues:96:5)
                    at Browser.wrapCommandFn (E:\MyWorkSpace\wdo-samples\wdio-jsappium\node_modules\@wdio\utils\build\shim.js:137:29)
                    at Context.&lt;anonymous> (E:\MyWorkSpace\wdo-samples\wdio-jsappium\test\specs\bigbasket\/TC02.setting.test.js:6:9)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>